### ISSUE TITLE
I've got a problem :KeyError: 'QCSCRATCH'

### ISSUE THREAD

**Issue by phoos123** [abelcarreras/qchem_scripts#1]
"C:\Program Files\Python37\python.exe" E:/pythonProject/ww.py
Traceback (most recent call last):
  File "E:/pythonProject/ww.py", line 19, in <module>
    read_fchk=True
  File "C:\Program Files\Python37\lib\site-packages\pyqchem\qchem_core.py", line 258, in get_output_from_qchem
    scratch = os.environ['QCSCRATCH']
  File "C:\Program Files\Python37\lib\os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'QCSCRATCH'

**Comment by abelcarreras** [comment]
Hi,

Thanks for your feedback.
It seems that either you didn't define QCSCRATCH environment variable or python is not picking it from the environment. Unfortunately I don't have a windows machine to test this.
Can you check if QCSCRATCH variable is defined?

**Comment by phoos123** [comment]
> Hi,
> 
> Thanks for your feedback.
> It seems that either you didn't define QCSCRATCH environment variable or python is not picking it from the environment. Unfortunately I don't have a windows machine to test this.
> Can you check if QCSCRATCH variable is defined?

thanks

**Comment by phoos123** [comment]
how can I set QCSCRATCH environment variable on windows

**Comment by abelcarreras** [comment]
I don't know. Unfortunately I have no experience installing Q-Chem on windows.
QCSCRATCH is a Q-Chem environment variable that contains the SCRATCH path (at least in UNIX-like systems).
If you have Q-Chem installed and running in your windows machine this variable should be set somehow.
Maybe you can check Q-Chem's manual for this.
