### ISSUE TITLE
get_output_from_qchem() , unable to properly read my QCSCRATCH directory

### ISSUE THREAD

**Issue by dominikusbrian** [abelcarreras/qchem_scripts#3]
Dear Abel,

I am reaching out to you, regarding the PyQchem module you written.
First of all, i must say it is a nicely written package.
I am facing an issue with using the PyQchem module to submit QChem job for me ,
I got the following error,

```
 in get_output_from_qchem(input_qchem, processors, use_mpi, scratch, read_fchk, parser, parser_parameters, force_recalculation, fchk_only, store_full_output, delete_scratch, remote, strict_policy)
    439     temp_filename = 'qchem_temp_{}.inp'.format(os.getpid())
    440 
--> 441     qchem_input_file = open(os.path.join(work_dir, temp_filename), mode='w')
    442     qchem_input_file.write(input_txt)
    443     qchem_input_file.close()

FileNotFoundError: [Errno 2] No such file or directory: 'None/qchem38993/qchem_temp_38993.inp'

```
From what I understand it does not properly read the temp_filename variable which should contain the QCSCRATCH address in the directory i.e. it is failing to properly execute the following line [attached below] inside the qchem_core.py

```
def get_output_from_qchem(input_qchem,
     .
     .
     .
    if scratch is None:
        scratch = os.getenv('QCSCRATCH')

    work_dir = '{}/qchem{}/'.format(scratch, os.getpid())

    try:
        os.mkdir(work_dir)
    .
    .

```
I am not sure how to fix the issue for reading the QCSCRATCH address properly, calling echo $QCSCRATCH directly from my bash shell command line give proper directory for the project. but it seems the os.getenv('QCSCRATCH') yield a result 'none'

if i modify it automatically by specifying it as follow:

```
data = get_output_from_qchem(qc_input,
                            processors=1,
                            scratch='/document/tutorial/autoQChem/pyqchem')
```
I still end up with this error saying this

```
 in get_output_from_qchem(input_qchem, processors, use_mpi, scratch, read_fchk, parser, parser_parameters, force_recalculation, fchk_only, store_full_output, delete_scratch, remote, strict_policy)
    451 
    452     if not finish_ok(output):
--> 453         raise OutputError(output, err)
    454 
    455     version = get_version_output(output)

OutputError: Error in Q-Chem calculation:
/bin/sh: None/exe/qcprog.exe: No such file or directory
```
Seems that it can't find my $QC executable directory automatically
Is there a way for me to include the proper QChem_env.sh that i have or to specify manually where my $QC is ?

Looking forward to your guidance,
Best regards,
Domi.

**Comment by abelcarreras** [comment]
Hi Domi,

Can you tell me more information about your system? OS, python version, shell, environment, qc installation, etc..
I rely in os.getenv() function to read the environment variables. As you may know 
this is part of the standard library.

Can you try to execute this command in a python console to check if you are
able to read the environment correctly from python? 

```
import os
print('QCSCRATCH:', os.getenv('QCSCRATCH'))
print('enviroment: ', os.environ) 
```

**Comment by abelcarreras** [comment]
Also you can try to set the environment at the beginning of the python script before calling pyqchem:

```
import os
os.environ['QC'] = '/dir_to_qchem/'
os.environ['QCSCRATCH'] = '/dir_to_qchem_scratch_dir/'
```

**Comment by abelcarreras** [comment]
Also if you type from bash
```
env
```
are the QC and QCSCRATCH variables listed?

**Comment by dominikusbrian** [comment]
Hi Abel, 

Thank you for the quick response, 
I tried the above tests, 
and I find out where the issue is,

pyqchem try to find the qcprog.exe in work_dir, 
in my qchem installation the name format comes in this form 
'/server/packages/qchem/5.1.1c/exe/qcprog.exe'

while the pyqchem default will try to find it here:
`/server/packages/qchem/5.1.1c/bin/qchem/exe/qcprog.exe`

This is specified inside the pyqchem qchem_core.py 
line 382 where it specifies for work_dir , it is specified as wor '{}/qchem/{}'.format(scratch, os.getpid())
to then give `work_dir = `/server/packages/qchem/5.1.1c/bin/qchem/exe/qcprog.exe``

Performing manual fix to this by specifying the work_dir without /bin/qchem/ , will work to overcome the original issue that initially report error saying :

```
OutputError                               Traceback (most recent call last)
<ipython-input-730-18012508f714> in <module>
----> 1 data = get_output_from_qchem(qc_input,
      2                             processors=1 )

/group/software/anaconda3/lib/python3.8/site-packages/pyqchem/qchem_core.py in get_output_from_qchem(input_qchem, processors, use_mpi, scratch, read_fchk, parser, parser_parameters, force_recalculation, fchk_only, store_full_output, delete_scratch, remote, strict_policy)
    451 
    452     if not finish_ok(output):
--> 453         raise OutputError(output, err)
    454 
    455     version = get_version_output(output)

OutputError: Error in Q-Chem calculation:
/bin/sh: /server/packages/qchem/5.1.1c/bin/qchem/exe/qcprog.exe: Not a directory
```

But then I encountered another issue , for which my scratch directory is different then my work_dir ,
so in line 441 when the get_output_from_qchem()
try to do 
`qchem_input_file = open(os.path.join(work_dir, temp_filename), mode='w')`
this point to incorrect folder,
in my case the fix is to point this to scratch , such that
`qchem_input_file = open(os.path.join(scratch, temp_filename), mode='w')`

with those two points dealt will, I then face another error which seems to come from the information passed to the , dependent module Popen and PIPE imported from the subprocess.

with error saying the following.

```
<ipython-input-16-c6cc2aa6ec78> in <module>
----> 1 data = qchem_core.get_output_from_qchem(qc_input,
      2                             processors=1)

/group/software/anaconda3/lib/python3.8/site-packages/pyqchem/qchem_core.py in get_output_from_qchem(input_qchem, processors, use_mpi, scratch, read_fchk, parser, parser_parameters, force_recalculation, fchk_only, store_full_output, delete_scratch, remote, strict_policy)
    447     if output is None or force_recalculation is True:
    448         if remote is None:
--> 449             output, err = local_run(temp_filename, work_dir, fchk_filename, use_mpi=use_mpi, processors=processors)
    450         else:
    451             output, err = remote_run(temp_filename, work_dir, fchk_filename, remote, use_mpi=use_mpi, processors=processors)

/group/software/anaconda3/lib/python3.8/site-packages/pyqchem/qchem_core.py in local_run(input_file_name, work_dir, fchk_file, use_mpi, processors)
    207     command = binary + ' {} '.format(os.path.join(work_dir, input_file_name)) + ' {} '.format(work_dir)
    208 
--> 209     qchem_process = Popen(command, stdout=PIPE, stdin=PIPE, stderr=PIPE, shell=True, cwd=work_dir)
    210     (output, err) = qchem_process.communicate()
    211     qchem_process.wait()

/group/software/anaconda3/lib/python3.8/subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors, text)
    852                             encoding=encoding, errors=errors)
    853 
--> 854             self._execute_child(args, executable, preexec_fn, close_fds,
    855                                 pass_fds, cwd, env,
    856                                 startupinfo, creationflags, shell,

/group/software/anaconda3/lib/python3.8/subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, restore_signals, start_new_session)
   1700                     if errno_num != 0:
   1701                         err_msg = os.strerror(errno_num)
-> 1702                     raise child_exception_type(errno_num, err_msg, err_filename)
   1703                 raise child_exception_type(err_msg)
   1704 

NotADirectoryError: [Errno 20] Not a directory: '/server/packages/qchem/5.1.1c/exe/qcprog.exe'
```
This seems to say that the way I am fixing the custom directory doesn't implement the fix globally and only effective for the get_output_from_qchem() particular function. 

I notice that due to this different directory structure (/exe/qcprog.exe that is not placed within the /bin/qchem/ ) when I am performing qchem calculation in my server manually(that is by writing the usual shell script) it is customary to first execute 
`source /gpfsnyu/packages/qchem/5.1.1c/qcenv.sh`

That's all I found so far,
Looking forward to your guidance,

Sincerely,
Domi.

**Comment by abelcarreras** [comment]
Hi Domi,

Maybe the directory structure is a little confusing. Let me clarify:
PyQchem expects two environment variables: QC and QCSCRATCH.

From QC, pyqchem figures out the binary path as:

```
$QC/exe/qcprog.exe
```

as you can see, $QC/bin/qchem script is ignored, it directly uses qcprog.exe.
This can be found in local_run function:

https://github.com/abelcarreras/PyQchem/blob/9ef397992b2d3a047a9dc57a232895f0df06c638/pyqchem/qchem_core.py#L186

From QCSCRATCH it generates a work directory where  the calculation runs and all the temp files are placed.
This is done by generating a $QCSCRATCH/qchem$PID directory  for each calculation (where PID is just the process identification number).

https://github.com/abelcarreras/PyQchem/blob/9ef397992b2d3a047a9dc57a232895f0df06c638/pyqchem/qchem_core.py#L382

In principle this is all pyqchem needs, these environment variables are not used outside of `get_output_from_qchem` and `local_run` functions. That's why as long as `qcprog.exe` is placed in $QC/exe/ and $QCSCRATCH exists you only need to make sure that python is reading these variables  (QC & QCSCRATCH) from the environemnt with `os.getenv`. That is why I asked you to do the test. https://github.com/abelcarreras/PyQchem/issues/3#issuecomment-808819574
If python is not reading thee variables properly I think the simplest way is to set this variables manually inside your python script as I wrote in my second suggestion. https://github.com/abelcarreras/PyQchem/issues/3#issuecomment-808822085

**Comment by abelcarreras** [comment]
I edited my previous post since the comments on QCSCRATCH were not correct. Now it is OK.

**Comment by dominikusbrian** [comment]
Hi Abel, thanks for your help. 

Yes specifying them explicitly as you suggested did help overcome the issues i faced earlier with the pyqchem. the get_output_from_qchem does read both QC and QCSCRATCH properly (e.g. if i print those variable within the function it gave proper directory).

Now what's left is dealing with this MPI issue (I have dealt with similar issue like this one before, so hopefully I can find where the asked library is located and provide it prior to calling the python script)

```
OutputError                               Traceback (most recent call last)
<ipython-input-19-443c5a226241> in <module>
----> 1 data = qchem_core.get_output_from_qchem(qc_input,
      2                             processors=1, use_mpi=True)

/group/software/anaconda3/lib/python3.8/site-packages/pyqchem/qchem_core.py in get_output_from_qchem(input_qchem, processors, use_mpi, scratch, read_fchk, parser, parser_parameters, force_recalculation, fchk_only, store_full_output, delete_scratch, remote, strict_policy)
    452 
    453     if not finish_ok(output):
--> 454         raise OutputError(output, err)
    455 
    456     version = get_version_output(output)

OutputError: Error in Q-Chem calculation:
/server/packages/qchem/5.1.1c/exe/qcprog.exe: error while loading shared libraries: libmpi_cxx.so.1: cannot open shared object file: No such file or directory
```

**Comment by dominikusbrian** [comment]
Issue solved ^^ 
Thanks for the help all along Abel.

Best,
Domi.
